# Generated by Django 3.2.12 on 2022-02-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.SmallIntegerField(default='0', verbose_name='COLOR'),
        ),
    ]
