# Generated by Django 3.2.12 on 2022-02-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.IntegerField(default='0', verbose_name='COLOR'),
        ),
    ]
