# Generated by Django 3.2.12 on 2022-02-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='board_posts',
        ),
    ]
